---
services:
  scenario:
    build:
      context: ..
      dockerfile: scenarios/one.dockerfile
    image: simple_scenario_one
    volumes:
    - ..:/scenario
    environment:
      ENV_VAR: scenario one
    links: []
volumes: {}
