---
version: "2"
services:
  scenario:
    build:
      context: ..
      dockerfile: scenarios/one.dockerfile
    image: ruby_scenario_one
    volumes:
    - "..:/scenario"
    - "bundle_one:/usr/local/bundle"
    environment:
      BUNDLE_GEMFILE: scenarios/one.gemfile
volumes:
  bundle_one: {}
