---
version: "2"
services:
  scenario:
    build:
      context: ..
      dockerfile: scenarios/two.dockerfile
    image: ruby_scenario_two
    volumes:
    - ..:/scenario
    - bundle_two:/usr/local/bundle
    environment:
      BUNDLE_GEMFILE: scenarios/two.gemfile
    links: []
volumes:
  bundle_two: {}
